sonar.organization=semko69
sonar.projectKey=Semko69_webapp
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
# On exclut de l'analyse les fichiers generes (rapport de couverture, deps)
sonar.exclusions=coverage/**,node_modules/**
